---
before:
  hooks:
    - go mod download

builds:
  - env:
      - CGO_ENABLED=0

archives:
  - replacements:
      darwin: Darwin
      linux: Linux
      windows: Windows
      386: i386
      amd64: x86_64

    files:
      - LICENSE
      - README.md
      - CHANGELOG.md

brew:
  commit_author:
    email: info@koenrouwhorst.nl
    name: "Koen Rouwhorst"
  description: "Fast Amazon S3 bucket enumeration tool for pentesters"
  github:
    name: homebrew-tools
    owner: koenrh
  name: s3enum

checksum:
  name_template: "checksums.txt"

snapshot:
  name_template: "{{ .Tag }}-next"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
